### ISSUE TITLE
Some OSM objects do not have styling

### ISSUE THREAD

**Issue by juliusgeo** [juliusgeo/OpenStreetMapParser2.jl#1]
Need to add more styles to account for things such as: hospitals, graveyards, etc.

**Comment by yeesian** [comment]
It's not ideal, but there are default styles for overpass turbo: https://wiki.openstreetmap.org/wiki/Overpass_turbo/MapCSS#overpass_turbo_-_Default_Style

**Comment by juliusgeo** [comment]
@yeesian 
I think that this is now resolved--I added styles for every tag of the most common types of OSM objects so now you can change the style for any tag by modifying it's entry in the dictionary. I think that now perhaps it might be useful to have some way of parsing MapCSS to change the styles.jl file so that the styles align. Maybe it would make sense to have a Style object that has the dictionary in it.
