### ISSUE TITLE
ERROR: MethodError: no method matching iterate(::XMLElement)

### ISSUE THREAD

**Issue by bsnyh** [juliusgeo/OpenStreetMapParser2.jl#4]
julia> xml,bbox = open_file("/Users/jack/Desktop/denmark.osm")
ERROR: MethodError: no method matching iterate(::XMLElement)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:589
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:589
  iterate(::ExponentialBackOff) at error.jl:171
  ...
Stacktrace:
 [1] indexed_iterate(::XMLElement, ::Int64) at ./tuple.jl:63
 [2] top-level scope at none:0

**Comment by juliusgeo** [comment]
open_file does not return a bounding box. I forgot to update the readme. Correct usage should be:
```julia
xml = open_file("/Users/jack/Desktop/denmark.osm")
way_arr, bbox = parse_ways(xml)
